# Generated by Django 5.1.1 on 2025-03-04 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=9)),
                ('cidade_id', models.IntegerField()),
                ('cidade_nome', models.CharField(max_length=255)),
                ('estado_id', models.IntegerField()),
                ('estado_sigla', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('representante_nome', models.CharField(max_length=255)),
                ('representante_cargo', models.CharField(max_length=100)),
                ('representante_cpf', models.CharField(max_length=14)),
                ('representante_rg', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/logos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração da Empresa',
                'verbose_name_plural': 'Configurações da Empresa',
                'db_table': 'configuracoes_empresa',
            },
        ),
    ]
